@startuml
actor Admin
agent Esp8266 [
ESP8266
Buffer bitmaps in RAM
]
agent Arduino [
Arduino
2 bitmaps in RAM
]
agent LedDisplay
node Director[
Director
===
Via webinterface
]
node Switchboard
storage Reporters {
node IRCBot [
IRC Bot
===
Network and channel
]

node Webscraper [
Sites scraper
===
Sites and patterns
]
node APIAccessor [
API Accessor
===
Sites and patterns
]
}
node Layout [
Layout
===
Places contents
Generates bitmap
]
storage Fontsets
storage Data
node Printer [
Printer
===
Push Bitmap over WIFI
]
Admin -- Director
cloud sites
cloud ircserver
Layout -- Data
Layout -- Fontsets
Switchboard -0)- Director
Switchboard -0)- Printer
Switchboard -0)- IRCBot
Switchboard -0)- Webscraper
Switchboard -0)- APIAccessor
Switchboard -0)-  Layout
Printer -0)- Esp8266
Webscraper --> sites
APIAccessor --> sites
IRCBot --> ircserver
Esp8266 == Arduino: Serial
Arduino == LedDisplay: Hardwired data referesh
@enduml